# Generated by Django 2.1b1 on 2018-09-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.IntegerField(default=0),
        ),
    ]
